;
; File generated by cc65 v 2.19 - Git c720c3c
;
	.fopt		compiler,"cc65 v 2.19 - Git c720c3c"
	.setcpu		"65SC02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_dfcl_wait
	.import		_dfcl_vbint
	.import		_dfcl_stick
	.import		_dfcl_sndconfig
	.import		_dfcl_sndchannel
	.import		_dfcl_mode
	.import		_dfcl_colour
	.import		_dfcl_ptinit
	.import		_dfcl_ptrun
	.import		_dfcl_ptload
	.import		_dfcl_sprpat
	.import		_dfcl_sprpos
	.import		_dfcl_sprcol
	.import		_dfcl_sprnme
	.import		_dfcl_vload
	.import		_star
	.import		_x_coord
	.import		_y_coord
	.export		_msg
	.export		_sprused
	.export		_int_v
	.export		_int_c
	.export		_vb_handler
	.export		_main

.segment	"DATA"

_msg:
	.byte	$4D,$41,$59,$20,$54,$48,$45,$20,$46,$4F,$55,$52,$54,$48,$20,$42
	.byte	$45,$20,$57,$49,$54,$48,$20,$59,$4F,$55,$20,$20,$20,$20,$20,$20
	.byte	$00

.segment	"RODATA"

S0002:
	.byte	$73,$74,$61,$72,$77,$61,$72,$73,$2E,$70,$74,$33,$00
S0003:
	.byte	$6D,$61,$79,$34,$00

.segment	"BSS"

_sprused:
	.res	32,$00
_int_v:
	.res	1,$00
_int_c:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ vb_handler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_vb_handler: near

.segment	"CODE"

	lda     _int_v
	cmp     #$10
	bcs     L0004
	lda     _int_c
	beq     L0005
	dec     _int_c
	rts
L0005:	lda     #$03
	sta     _int_c
	lda     #$1F
	jsr     pusha
	lda     _int_v
	jsr     _dfcl_sprnme
	inc     _int_v
L0004:	rts

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldy     #$09
	jsr     subysp
	lda     #$11
	jsr     _dfcl_mode
	lda     #$20
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     _dfcl_colour
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	ldx     #$80
	lda     #$00
	jsr     _dfcl_ptload
	ldy     #$07
	jsr     staxysp
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	ldx     #$00
	txa
	jsr     _dfcl_vload
	ldy     #$07
	jsr     staxysp
	ldx     #$00
	txa
	ldy     #$07
	jsr     staxysp
L0002:	ldy     #$08
	jsr     ldaxysp
	cmp     #$20
	txa
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	asl     a
	lda     #$00
	tax
	jcc     L0039
	ldy     #$07
	lda     (c_sp),y
	jsr     pusha
	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	txa
	clc
	adc     #>(_msg)
	sta     ptr1+1
	ldy     #<(_msg)
	lda     (ptr1),y
	jsr     _dfcl_sprnme
	ldy     #$07
	lda     (c_sp),y
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$C8
	jsr     _dfcl_sprpos
	ldy     #$07
	lda     (c_sp),y
	jsr     pusha
	lda     #$0F
	jsr     _dfcl_sprcol
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	txa
	clc
	adc     #>(_msg)
	sta     ptr1+1
	ldy     #<(_msg)
	lda     (ptr1),y
	cmp     #$20
	bne     L0007
	ldy     #$08
	jsr     ldaxysp
	clc
	adc     #<(_sprused)
	sta     ptr1
	txa
	adc     #>(_sprused)
	sta     ptr1+1
	lda     #$00
	bra     L0048
L0007:	ldy     #$08
	jsr     ldaxysp
	clc
	adc     #<(_sprused)
	sta     ptr1
	txa
	adc     #>(_sprused)
	sta     ptr1+1
	lda     #$01
L0048:	sta     (ptr1)
	ldy     #$07
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
L0039:	ldy     #$07
	jsr     staxysp
L0009:	ldy     #$08
	jsr     ldaxysp
	cmp     #$10
	txa
	sbc     #$00
	bvc     L000D
	eor     #$80
L000D:	bpl     L003A
	ldy     #$07
	lda     (c_sp),y
	jsr     pusha
	ldy     #$09
	jsr     ldaxysp
	jsr     aslax3
	clc
	adc     #<(_star)
	tay
	txa
	adc     #>(_star)
	tax
	tya
	jsr     _dfcl_sprpat
	ldy     #$07
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	bra     L0009
L003A:	lda     #$07
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     pusha
	tax
	jsr     _dfcl_sndconfig
	ldx     #$00
	lda     #$64
	ldy     #$05
	jsr     staxysp
L000E:	ldy     #$06
	jsr     ldaxysp
	cmp     #$D0
	txa
	sbc     #$07
	bvc     L0012
	eor     #$80
L0012:	bpl     L000F
	lda     #$01
	jsr     pusha
	lda     #$0A
	jsr     pusha
	ldy     #$08
	jsr     ldaxysp
	jsr     _dfcl_sndchannel
	lda     #$02
	jsr     pusha
	lda     #$0A
	jsr     pusha
	ldy     #$08
	jsr     ldaxysp
	jsr     incax4
	jsr     _dfcl_sndchannel
	ldx     #$00
	lda     #$01
	jsr     _dfcl_wait
	ldy     #$05
	ldx     #$00
	lda     #$0F
	jsr     addeqysp
	bra     L000E
L000F:	ldx     #$01
	lda     #$2C
	jsr     _dfcl_wait
	lda     #$1F
	jsr     pusha
	lda     #$00
	jsr     _dfcl_sprnme
	lda     #$1F
	jsr     pusha
	lda     #$63
	jsr     pusha
	lda     #$3C
	jsr     _dfcl_sprpos
	lda     #$1F
	jsr     pusha
	lda     #$0F
	jsr     _dfcl_sprcol
	stz     _int_c
	stz     _int_v
	lda     #<(_vb_handler)
	ldx     #>(_vb_handler)
	jsr     _dfcl_vbint
	ldx     #$00
	lda     #$0F
	ldy     #$07
	jsr     staxysp
L0013:	ldy     #$08
	jsr     ldaxysp
	txa
	bmi     L0014
	lda     #$03
	jsr     pusha
	ldy     #$08
	lda     (c_sp),y
	jsr     pusha
	ldx     #$00
	lda     #$23
	jsr     _dfcl_sndchannel
	ldx     #$00
	lda     #$03
	jsr     _dfcl_wait
	ldx     #$00
	lda     #$01
	ldy     #$07
	jsr     subeqysp
	bra     L0013
L0014:	ldx     #$00
	lda     #$64
	jsr     _dfcl_wait
	ldx     #$00
	lda     #$0A
	ldy     #$07
	jsr     staxysp
L0017:	ldy     #$08
	jsr     ldaxysp
	txa
	bmi     L0018
	lda     #$01
	jsr     pusha
	ldy     #$08
	lda     (c_sp),y
	jsr     pusha
	ldy     #$08
	jsr     ldaxysp
	jsr     _dfcl_sndchannel
	lda     #$02
	jsr     pusha
	ldy     #$08
	lda     (c_sp),y
	jsr     pusha
	ldy     #$08
	jsr     ldaxysp
	jsr     incax4
	jsr     _dfcl_sndchannel
	ldx     #$00
	lda     #$14
	jsr     _dfcl_wait
	ldx     #$00
	lda     #$01
	ldy     #$07
	jsr     subeqysp
	bra     L0017
L0018:	lda     #$01
	tay
	sta     (c_sp),y
	ldx     #$80
	dea
	jsr     pushax
	jsr     _dfcl_ptinit
	ldx     #$00
	txa
	ldy     #$07
	jsr     staxysp
	ldy     #$02
	sta     (c_sp),y
L004A:	sta     (c_sp)
L001B:	ldy     #$08
	jsr     ldaxysp
	ldy     #$05
	jsr     staxysp
	ldx     #$00
	txa
	ldy     #$03
	jsr     staxysp
L001E:	ldy     #$04
	jsr     ldaxysp
	cmp     #$20
	txa
	sbc     #$00
	bvc     L0022
	eor     #$80
L0022:	asl     a
	ldx     #$00
	bcc     L003B
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	txa
	clc
	adc     #>(_sprused)
	sta     ptr1+1
	ldy     #<(_sprused)
	lda     (ptr1),y
	beq     L0023
	ldy     #$03
	lda     (c_sp),y
	jsr     pusha
	ldy     #$07
	jsr     ldaxysp
	sta     ptr1
	txa
	clc
	adc     #>(_x_coord)
	sta     ptr1+1
	ldy     #<(_x_coord)
	lda     (ptr1),y
	jsr     pusha
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	txa
	clc
	adc     #>(_y_coord)
	sta     ptr1+1
	ldy     #<(_y_coord)
	lda     (ptr1),y
	jsr     _dfcl_sprpos
L0023:	ldy     #$05
	ldx     #$00
	lda     #$06
	jsr     addeqysp
	ldy     #$06
	jsr     ldaxysp
	cmp     #$00
	txa
	sbc     #$01
	bvs     L0025
	eor     #$80
L0025:	bpl     L0020
	ldx     #$00
	lda     #$FF
	ldy     #$05
	jsr     subeqysp
L0020:	ldy     #$03
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L001E
L003B:	lda     #$02
	jsr     _dfcl_wait
	ldx     #$00
	lda     #$01
	ldy     #$07
	jsr     subeqysp
	ldy     #$08
	jsr     ldaxysp
	cpx     #$80
	bcc     L0026
	ldx     #$00
	lda     #$FF
	ldy     #$07
	jsr     staxysp
L0026:	ldy     #$0A
	jsr     pushwysp
	ldy     #$00
	ldx     #$00
	lda     #$40
	jsr     tosmoda0
	stx     tmp1
	ora     tmp1
	bne     L0027
	ldy     #$02
	clc
	ina
	adc     (c_sp),y
	sta     (c_sp),y
	cmp     #$06
	bcc     L003D
	lda     #$00
	sta     (c_sp),y
L003D:	lda     (c_sp),y
	beq     L003E
	cmp     #$01
	beq     L003F
	cmp     #$02
	beq     L0040
	cmp     #$03
	beq     L0041
	cmp     #$04
	beq     L0042
	bra     L0043
L003E:	lda     #$1F
	jsr     pusha
	lda     #$0A
	jsr     pusha
	bra     L0037
L003F:	lda     #$1F
	jsr     pusha
	lda     #$C8
	jsr     pusha
	lda     #$B4
	bra     L0037
L0040:	lda     #$1F
	jsr     pusha
	lda     #$32
	jsr     pusha
	lda     #$78
	bra     L0037
L0041:	lda     #$1F
	jsr     pusha
	lda     #$64
	jsr     pusha
	lda     #$50
	bra     L0037
L0042:	lda     #$1F
	jsr     pusha
	lda     #$B4
	jsr     pusha
	lda     #$14
	bra     L0037
L0043:	lda     #$1F
	jsr     pusha
	lda     #$50
	jsr     pusha
	lda     #$32
L0037:	jsr     _dfcl_sprpos
	stz     _int_v
L0027:	lda     #$80
	jsr     _dfcl_stick
	tax
	jeq     L004A
	lda     (c_sp)
	jne     L001B
	ina
	sta     (c_sp)
	tay
	lda     (c_sp),y
	eor     #$01
	sta     (c_sp),y
	lda     (c_sp),y
	beq     L0045
	tya
	jsr     _dfcl_ptrun
	jmp     L001B
L0045:	jsr     _dfcl_ptrun
	jmp     L001B

.endproc

