;
; File generated by cc65 v 2.19 - Git c720c3c
;
	.fopt		compiler,"cc65 v 2.19 - Git c720c3c"
	.setcpu		"65SC02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_getchar
	.import		_printf
	.import		_scanf
	.export		_delay
	.export		_main

.segment	"RODATA"

S0004:
	.byte	$54,$68,$65,$20,$73,$74,$72,$69,$6E,$67,$20,$77,$61,$73,$20,$25
	.byte	$73,$0D,$00
S0002:
	.byte	$45,$6E,$74,$65,$72,$20,$73,$6F,$6D,$65,$74,$68,$69,$6E,$67,$3A
	.byte	$20,$00
S0001:
	.byte	$48,$65,$6C,$6C,$6F,$20,$77,$6F,$72,$6C,$64,$0D,$00
S0005:
	.byte	$25,$64,$20,$00
S0007	:=	S0005+0
S0003:
	.byte	$25,$73,$00
S0006	:=	S0004+17

; ---------------------------------------------------------------
; void __near__ delay (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_delay: near

.segment	"CODE"

	jsr     decsp2
	ldx     #$00
	txa
	jsr     stax0sp
L0002:	jsr     ldax0sp
	cmp     #$10
	txa
	sbc     #$27
	bvc     L0006
	eor     #$80
L0006:	bpl     L0003
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	ldx     #$00
	lda     #$01
	jsr     subeq0sp
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	bra     L0002
L0003:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldy     #$0D
	jsr     subysp
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jsr     _delay
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	ldy     #$04
	jsr     _scanf
	lda     #<(S0004)
	ldx     #>(S0004)
	jsr     pushax
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	ldy     #$04
	jsr     _printf
	ldx     #$00
	txa
	jsr     stax0sp
	bra     L0004
L0002:	lda     #<(S0005)
	ldx     #>(S0005)
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     incax5
	jsr     leaaxsp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha0
	ldy     #$04
	jsr     _printf
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	jsr     _delay
L0004:	jsr     ldax0sp
	jsr     incax3
	jsr     leaaxsp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	bne     L0002
	lda     #<(S0006)
	ldx     #>(S0006)
	jsr     pushax
	ldy     #$02
	jsr     _printf
L0005:	jsr     _getchar
	ldy     #$02
	sta     (c_sp),y
	lda     #<(S0007)
	ldx     #>(S0007)
	jsr     pushax
	ldy     #$04
	lda     (c_sp),y
	jsr     pusha0
	ldy     #$04
	jsr     _printf
	ldy     #$02
	lda     (c_sp),y
	cmp     #$0D
	bne     L0005
	ldx     #$AD
	lda     #$DE
	rts

.endproc

