# Script to build an include file of cross-bank call locations for the
# HB128 Breadboard Computer
# This is a multi-rom build with cross-rom calls
# Requires the as65 assembler as preproceesing is done using symbol tables
try {

  $startTime = (Get-Date)

  # Source file for actual call locations
  $source = "../../../build/bank/bank"

  # File for autogenerated cross-bank locations
  $autogen = "hb128.inc"

#  # File containing cross-bank (external) locations
#  $extern = "../../../build/bank/extern.mak"

  # Initial binary creating symbol table with dummy values
  Write-Output "Generating include file for externals"

  # Initial comment line in the dummy autogen file
  Set-Content -Value "; This file is autogenerated" -Path $autogen


  $pattern = " : $"
  $list = New-Object System.Collections.ArrayList

  # Process each extern reference
  for($i=0; $i -lt 4; $i++) {
    $list.Clear()
    # Read each line from the bank symbol table
    $bank = ""+$i+".sym"
    Write-Output ("Processing bank"+$bank)
    $lines = Get-Content -Path ($source+$bank)
    foreach ($line in $lines) {
      if ($line.IndexOf($pattern) -ne -1) {
        # add double underscore label and the address
        $array = $line.Split(":")
        if ($array[0].Trim().Substring(0,1) -ne ".") {
          [void]$list.Add("_dfcl"+$i+"_"+$array[0].Trim()+" ="+$array[1].Substring(0,6))
        }
      }
    }
    Add-Content -Value $list -Path $autogen
  }

  # Remove duplicate lines
  Write-Output "Removing duplicate lines"
  $uniqueLines = Get-Content -Path $autogen | Sort-Object -Unique
  Set-Content -Value $uniqueLines -Path $autogen

  # Final build complete message and timing
  Write-Output ("Generate completed in   :"+((Get-Date)-$startTime)+" seconds")
}
catch {
  Write-Output "ERRORS"
}
