;
; File generated by cc65 v 2.19 - Git c720c3c
;
	.fopt		compiler,"cc65 v 2.19 - Git c720c3c"
	.setcpu		"65SC02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_hbputc
	.export		_write

; ---------------------------------------------------------------
; int __near__ __fastcall__ write (int fd, const void *buf, unsigned int count)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_write: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	ldy     #$07
	jsr     pushwysp
	ldx     #$00
	txa
	ldy     #$02
	jsr     staxysp
L0002:	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	cmp     (c_sp),y
	txa
	iny
	sbc     (c_sp),y
	bcs     L0006
	jsr     ldptr10sp
	lda     (ptr1)
	pha
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	pla
	jsr     _hbputc
	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	bra     L0002
L0006:	jsr     ldaxysp
	ldy     #$0A
	jmp     addysp

.endproc

